### QT ###
set(QT_VERSION "6.3.0" CACHE STRING "Currently installed Qt version")
if(WIN32)
    set(QT_DIR "C:/Qt/${QT_VERSION}/msvc2019_64/lib/cmake/Qt6" CACHE PATH "Qt directory")
elseif(UNIX)
    if(IS_DIRECTORY "$ENV{HOME}/Qt/${QT_VERSION}/gcc_64/lib/cmake/Qt6")
        set(QT_DIR "$ENV{HOME}/Qt/${QT_VERSION}/gcc_64/lib/cmake/Qt6" CACHE PATH "Qt directory")
    elseif(IS_DIRECTORY "/usr/local/Qt-${QT_VERSION}/lib/cmake/Qt6")
        set(QT_DIR "/usr/local/Qt-${QT_VERSION}/lib/cmake/Qt6" CACHE PATH "Qt directory")
    else()
        set(QT_DIR "QT_DIR-NOTFOUND" CACHE PATH "Qt directory")
    endif()

    if(IS_DIRECTORY ${QT_DIR})
        set(Qt6DBusTools_DIR "${QT_DIR}DBusTools")
        set(Qt6BundledPcre2_DIR "${QT_DIR}BundledPcre2")
        set(Qt6BundledHarfbuzz_DIR "${QT_DIR}BundledHarfbuzz")
        set(Qt6BundledLibjpeg_DIR "${QT_DIR}BundledLibjpeg")
    endif()
endif()

if(IS_DIRECTORY ${QT_DIR})
    set(Qt6_DIR "${QT_DIR}")
    set(Qt6CoreTools_DIR "${QT_DIR}CoreTools")
    set(Qt6GuiTools_DIR "${QT_DIR}GuiTools")
    set(Qt6WidgetsTools_DIR "${QT_DIR}WidgetsTools")
endif()

list(APPEND QT_COMPONENTS Core Gui Widgets OpenGL Concurrent)
foreach (qt_component ${QT_COMPONENTS})
    list(APPEND QT_LINKS
        Qt${QT_VERSION_MAJOR}::${qt_component}
    )
endforeach()
if(ANDROID)
    list(APPEND QT_LINKS Qt${QT_VERSION_MAJOR}::CorePrivate)
endif()

find_package(QT NAMES Qt6 COMPONENTS ${QT_COMPONENTS} REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS ${QT_COMPONENTS} REQUIRED)

list(APPEND Engine3D_LIBRARIES ${QT_LINKS})

### GLM ###
if(WIN32)
    list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/include/3rdParty/glm)
else()
    find_package(glm)
endif()

if(WIN32)
    include(${Engine3D_DIR}/Engine3DExtras.cmake)
    ### CONTROLLER ###
    if(WITH_CONTROLLER)
        add_compile_definitions(HAVE_CONTROLLER)
    endif()

    ### OpenCV ###
    if(WITH_OPENCV)
        set(WITH_OPENCV true)
        add_compile_definitions(HAVE_OPENCV)

        list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/include/3rdParty/OpenCV)
        list(APPEND Engine3D_LIBRARIES_DIRS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/OpenCV)
        # file(GLOB OpenCV_LIBS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/OpenCV)
        foreach(OpenCV_COMPONENT ${OpenCV_COMPONENTS})
            list(APPEND OpenCV_LIBS opencv_${OpenCV_COMPONENT}${OpenCV_VERSION}$<$<CONFIG:Debug>:d>)
        endforeach()
        list(APPEND Engine3D_LIBRARIES ${OpenCV_LIBS})
    endif()

    ### ViSP ###
    if(WITH_VISP)
        set(WITH_VISP true)
        add_compile_definitions(HAVE_VISP)

        set(VISP_DIR ${Engine3D_DIR}/3rdParty/ViSP)
        find_package(VISP COMPONENTS ${VISP_COMPONENTS} REQUIRED)
        set(VISP_INCLUDE_DIRS ${VISP_DIR}/include)
        set(VISP_LIBRARIES_DIR ${VISP_DIR}/${VISP_ARCH}/${VISP_RUNTIME}/lib)

        # list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/include/3rdParty/ViSP)
        # list(APPEND Engine3D_LIBRARIES_DIRS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/ViSP)
        # # file(GLOB VISP_LIBS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/ViSP)
        foreach(VISP_COMPONENT ${VISP_COMPONENTS})
            list(APPEND VISP_LIBS visp_${VISP_COMPONENT}${VISP_VERSION_MAJOR}${VISP_VERSION_MINOR}${VISP_VERSION_PATCH}$<$<CONFIG:Debug>:d>)
        endforeach()
        list(APPEND Engine3D_LIBRARIES_DIRS ${VISP_LIBRARIES_DIR})
        list(APPEND Engine3D_LIBRARIES ${VISP_LIBS})
    endif()

    ### OpenVR ###
    if(WITH_VR)
        set(WITH_VR true)
        add_compile_definitions(HAVE_VR)

        list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/include/3rdParty/OpenVR)
        list(APPEND Engine3D_LIBRARIES_DIRS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/OpenVR)
        file(GLOB OPENVR_LIBS ${Engine3D_DIR}/lib/$<CONFIG>/3rdParty/OpenVR)
        list(APPEND Engine3D_LIBRARIES ${OPENVR_LIBS})
    endif()
elseif(UNIX)
    include(${Engine3D_DIR}/Engine3DExtras.cmake)
    if(WITH_CONTROLLER)
        add_compile_definitions(HAVE_CONTROLLER)
    endif()
    if(WITH_OPENCV)
        add_compile_definitions(HAVE_OPENCV)
        find_package(OpenCV REQUIRED)
        list(APPEND Engine3D_INCLUDE_DIRS ${OpenCV_INCLUDE_DIRS})
    endif()
    if(WITH_VISP)
        add_compile_definitions(HAVE_VISP)
        find_package(VISP COMPONENTS ${VISP_COMPONENTS} REQUIRED)
        list(APPEND Engine3D_INCLUDE_DIRS ${VISP_INCLUDE_DIRS})
        list(APPEND Engine3D_LIBRARIES ${VISP_LIBRARIES})
    endif()
    if(WITH_VR)
        add_compile_definitions(HAVE_VR)
        list(APPEND Engine3D_LIBRARIES /usr/lib/x86_64-linux-gnu/libopenvr_api.so)
    endif()
endif()

### Engine3D ###
if(WIN32)
    list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/include)
    list(APPEND Engine3D_LIBRARIES ${Engine3D_DIR}/lib/$<CONFIG>/Engine3D$<$<CONFIG:Debug>:d>.lib)
    set(Engine3D_DLL ${Engine3D_DIR}/bin/$<CONFIG>/Engine3D$<$<CONFIG:Debug>:d>.dll)
    set(Engine3D_EXTRA_DLL_DIR ${Engine3D_DIR}/bin/$<CONFIG>/3rdParty/)
elseif(UNIX AND NOT ANDROID)
    list(APPEND Engine3D_INCLUDE_DIRS /usr/include/Engine3D)
    list(APPEND Engine3D_LIBRARIES_DIRS /usr/lib)
    list(APPEND Engine3D_LIBRARIES Engine3D$<$<CONFIG:Debug>:d>)
elseif(ANDROID)
    list(APPEND Engine3D_INCLUDE_DIRS ${Engine3D_DIR}/../../../include/Engine3D)
    list(APPEND Engine3D_LIBRARIES_DIRS ${Engine3D_DIR}/../../../lib)
    list(APPEND Engine3D_LIBRARIES Engine3D$<$<CONFIG:Debug>:d>)
endif()

link_directories(${Engine3D_LIBRARIES_DIRS})